# Generated by Django 5.1.6 on 2025-02-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Player',
        ),
    ]
