# Generated by Django 5.1.6 on 2025-05-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batting',
            options={'ordering': ['year']},
        ),
        migrations.RemoveIndex(
            model_name='batting',
            name='player_data_runs_eea5e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='pitching',
            name='player_data_wins_5a27d5_idx',
        ),
    ]
